replicaCount: 1

image:
  repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/ofir/k8s-workshop
  tag: "wordpress"
  pullPolicy: IfNotPresent

env:
  WORDPRESS_DB_HOST: "mariadb"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_PASSWORD: "wordpress"
  WORDPRESS_DB_NAME: "wordpress"

persistence:
  enabled: true
  storageClass: ebs-sc-nitzanim
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  persistentVolumeClaimName: wordpress-pvc-ofir

namespace: ofir1

